/**
 * Centralized mock data for all WMS entities.
 * Used when USE_MOCK_DATA=true (no database connected).
 * When switching to real DB, replace these imports with server action calls.
 */

export const mockClients = [
  {
    id: "1",
    code: "ACME",
    name: "Acme Corporation",
    contactName: "John Smith",
    contactEmail: "john@acme.com",
    contactPhone: "555-0100",
    address: "456 Commerce St",
    city: "Houston",
    state: "TX",
    country: "US",
    zipCode: "77001",
    taxId: "12-3456789",
    notes: null,
    isActive: true,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "2",
    code: "GLOBEX",
    name: "Globex Industries",
    contactName: "Maria Garcia",
    contactEmail: "maria@globex.com",
    contactPhone: "555-0200",
    address: "789 Industrial Blvd",
    city: "Miami",
    state: "FL",
    country: "US",
    zipCode: "33101",
    taxId: "98-7654321",
    notes: "Temperature-sensitive goods",
    isActive: true,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-03-10"),
  },
  {
    id: "3",
    code: "INITECH",
    name: "Initech Logistics",
    contactName: "Bob Porter",
    contactEmail: "bob@initech.com",
    contactPhone: "555-0300",
    address: "321 Supply Chain Dr",
    city: "Dallas",
    state: "TX",
    country: "US",
    zipCode: "75201",
    taxId: null,
    notes: null,
    isActive: true,
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "4",
    code: "WAYNE",
    name: "Wayne Enterprises",
    contactName: "Lucius Fox",
    contactEmail: "lucius@wayne.com",
    contactPhone: "555-0400",
    address: "1 Wayne Tower",
    city: "Chicago",
    state: "IL",
    country: "US",
    zipCode: "60601",
    taxId: null,
    notes: "Account suspended — pending contract renewal",
    isActive: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "5",
    code: "STARK",
    name: "Stark Shipping Co",
    contactName: "Pepper Potts",
    contactEmail: "pepper@stark.com",
    contactPhone: "555-0500",
    address: "10880 Malibu Point",
    city: "Los Angeles",
    state: "CA",
    country: "US",
    zipCode: "90265",
    taxId: "55-1234567",
    notes: null,
    isActive: true,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-15"),
  },
];

export const mockProducts = [
  {
    id: "1",
    sku: "WIDGET-001",
    name: "Standard Widget",
    description: "Standard steel widget, powder-coated",
    clientId: "1",
    baseUom: "EA",
    weight: 0.5,
    weightUnit: "lb",
    hsCode: "7326.90",
    trackLot: false,
    trackSerial: false,
    minStock: 50,
    maxStock: 500,
    isActive: true,
    client: { code: "ACME", name: "Acme Corporation" },
  },
  {
    id: "2",
    sku: "GADGET-001",
    name: "Premium Gadget",
    description: "Electronic gadget with LCD display",
    clientId: "1",
    baseUom: "EA",
    weight: 1.2,
    weightUnit: "lb",
    hsCode: "8543.70",
    trackLot: true,
    trackSerial: false,
    minStock: 25,
    maxStock: 200,
    isActive: true,
    client: { code: "ACME", name: "Acme Corporation" },
  },
  {
    id: "3",
    sku: "PART-A100",
    name: "Component Part A-100",
    description: "Precision machined component",
    clientId: "1",
    baseUom: "EA",
    weight: 0.1,
    weightUnit: "lb",
    hsCode: "8487.90",
    trackLot: false,
    trackSerial: true,
    minStock: 100,
    maxStock: 1000,
    isActive: true,
    client: { code: "ACME", name: "Acme Corporation" },
  },
  {
    id: "4",
    sku: "BOLT-M8X40",
    name: "M8x40 Hex Bolt",
    description: "Grade 8.8 hex bolt, zinc plated",
    clientId: "2",
    baseUom: "EA",
    weight: 0.025,
    weightUnit: "lb",
    hsCode: "7318.15",
    trackLot: true,
    trackSerial: false,
    minStock: 200,
    maxStock: 5000,
    isActive: true,
    client: { code: "GLOBEX", name: "Globex Industries" },
  },
  {
    id: "5",
    sku: "PIPE-SCH40",
    name: 'Schedule 40 Steel Pipe 2"',
    description: "ASTM A53 Grade B, 2 inch, Schedule 40",
    clientId: "2",
    baseUom: "FT",
    weight: 3.65,
    weightUnit: "lb",
    hsCode: "7304.19",
    trackLot: true,
    trackSerial: false,
    minStock: 100,
    maxStock: 1000,
    isActive: true,
    client: { code: "GLOBEX", name: "Globex Industries" },
  },
  {
    id: "6",
    sku: "VALVE-BV2",
    name: '2" Ball Valve',
    description: "Full port brass ball valve, 2 inch",
    clientId: "3",
    baseUom: "EA",
    weight: 2.8,
    weightUnit: "lb",
    hsCode: "8481.80",
    trackLot: false,
    trackSerial: true,
    minStock: 10,
    maxStock: 100,
    isActive: true,
    client: { code: "INITECH", name: "Initech Logistics" },
  },
  {
    id: "7",
    sku: "MOTOR-3HP",
    name: "3HP Electric Motor",
    description: "TEFC 3-phase motor, 1750 RPM",
    clientId: "5",
    baseUom: "EA",
    weight: 45,
    weightUnit: "lb",
    hsCode: "8501.52",
    trackLot: false,
    trackSerial: true,
    minStock: 5,
    maxStock: 20,
    isActive: false,
    client: { code: "STARK", name: "Stark Shipping" },
  },
];

export const mockWarehouses = [
  {
    id: "1",
    code: "WH1",
    name: "Main Warehouse",
    address: "123 Logistics Ave, Houston TX",
    isActive: true,
    zones: [
      {
        id: "z1",
        code: "A",
        name: "Zone A - General Storage",
        type: "storage",
        binCount: 80,
      },
      { id: "z2", code: "B", name: "Zone B - Bulk Storage", type: "storage", binCount: 32 },
      { id: "z3", code: "S", name: "Staging Area", type: "staging", binCount: 16 },
    ],
  },
  {
    id: "2",
    code: "WH2",
    name: "Cold Storage Annex",
    address: "125 Logistics Ave, Houston TX",
    isActive: true,
    zones: [
      { id: "z4", code: "C", name: "Cold Zone", type: "storage", binCount: 48 },
      { id: "z5", code: "D", name: "Dock Area", type: "dock", binCount: 8 },
    ],
  },
];

export const mockShipments = [
  {
    id: "1",
    shipmentNumber: "ASN-2026-0001",
    status: "completed",
    carrier: "FedEx Freight",
    trackingNumber: "FXF-123456789",
    bolNumber: "BOL-2026-0038",
    poNumber: "PO-ACME-5678",
    expectedDate: "2026-03-10",
    arrivedDate: "2026-03-10",
    completedDate: "2026-03-10",
    notes: null,
    createdAt: "2026-03-08",
    clientId: "1",
    client: { code: "ACME", name: "Acme Corporation" },
    _count: { lines: 3, transactions: 5, discrepancies: 0 },
  },
  {
    id: "2",
    shipmentNumber: "ASN-2026-0002",
    status: "receiving",
    carrier: "XPO Logistics",
    trackingNumber: "XPO-789456123",
    bolNumber: "BOL-2026-0042",
    poNumber: "PO-GLX-1234",
    expectedDate: "2026-03-15",
    arrivedDate: "2026-03-15",
    completedDate: null,
    notes: "Fragile items — handle with care. Dock door 3.",
    createdAt: "2026-03-12",
    clientId: "2",
    client: { code: "GLOBEX", name: "Globex Industries" },
    _count: { lines: 5, transactions: 2, discrepancies: 1 },
  },
  {
    id: "3",
    shipmentNumber: "ASN-2026-0003",
    status: "arrived",
    carrier: "SAIA",
    trackingNumber: "SAIA-456789012",
    bolNumber: "BOL-2026-0045",
    poNumber: null,
    expectedDate: "2026-03-16",
    arrivedDate: "2026-03-16",
    completedDate: null,
    notes: null,
    createdAt: "2026-03-13",
    clientId: "3",
    client: { code: "INITECH", name: "Initech Logistics" },
    _count: { lines: 2, transactions: 0, discrepancies: 0 },
  },
  {
    id: "4",
    shipmentNumber: "ASN-2026-0004",
    status: "expected",
    carrier: "Old Dominion",
    trackingNumber: null,
    bolNumber: null,
    poNumber: "PO-STK-9012",
    expectedDate: "2026-03-18",
    arrivedDate: null,
    completedDate: null,
    notes: "24 pallets, requires forklift",
    createdAt: "2026-03-14",
    clientId: "5",
    client: { code: "STARK", name: "Stark Shipping Co" },
    _count: { lines: 4, transactions: 0, discrepancies: 0 },
  },
  {
    id: "5",
    shipmentNumber: "ASN-2026-0005",
    status: "draft",
    carrier: null,
    trackingNumber: null,
    bolNumber: null,
    poNumber: null,
    expectedDate: null,
    arrivedDate: null,
    completedDate: null,
    notes: null,
    createdAt: "2026-03-16",
    clientId: "1",
    client: { code: "ACME", name: "Acme Corporation" },
    _count: { lines: 0, transactions: 0, discrepancies: 0 },
  },
];

export const mockInventory = [
  {
    id: "1",
    onHand: 150,
    allocated: 20,
    available: 130,
    lotNumber: null,
    serialNumber: null,
    uom: "EA",
    product: { sku: "WIDGET-001", name: "Standard Widget", client: { code: "ACME" } },
    bin: {
      barcode: "WH1-A-01-01-01-01",
      shelf: { rack: { aisle: { zone: { code: "A", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "2",
    onHand: 75,
    allocated: 0,
    available: 75,
    lotNumber: "LOT-2026-001",
    serialNumber: null,
    uom: "EA",
    product: { sku: "GADGET-001", name: "Premium Gadget", client: { code: "ACME" } },
    bin: {
      barcode: "WH1-A-01-01-01-03",
      shelf: { rack: { aisle: { zone: { code: "A", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "3",
    onHand: 500,
    allocated: 100,
    available: 400,
    lotNumber: "LOT-2026-003",
    serialNumber: null,
    uom: "EA",
    product: { sku: "BOLT-M8X40", name: "M8x40 Hex Bolt", client: { code: "GLOBEX" } },
    bin: {
      barcode: "WH1-B-02-01-01-05",
      shelf: { rack: { aisle: { zone: { code: "B", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "4",
    onHand: 30,
    allocated: 5,
    available: 25,
    lotNumber: null,
    serialNumber: "SN-00234",
    uom: "EA",
    product: { sku: "VALVE-BV2", name: '2" Ball Valve', client: { code: "INITECH" } },
    bin: {
      barcode: "WH1-A-01-02-01-02",
      shelf: { rack: { aisle: { zone: { code: "A", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "5",
    onHand: 200,
    allocated: 0,
    available: 200,
    lotNumber: "LOT-2026-005",
    serialNumber: null,
    uom: "FT",
    product: {
      sku: "PIPE-SCH40",
      name: 'Schedule 40 Steel Pipe 2"',
      client: { code: "GLOBEX" },
    },
    bin: {
      barcode: "WH1-B-02-02-01-01",
      shelf: { rack: { aisle: { zone: { code: "B", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "6",
    onHand: 0,
    allocated: 0,
    available: 0,
    lotNumber: null,
    serialNumber: null,
    uom: "EA",
    product: { sku: "MOTOR-3HP", name: "3HP Electric Motor", client: { code: "STARK" } },
    bin: {
      barcode: "WH2-C-01-01-01-01",
      shelf: { rack: { aisle: { zone: { code: "C", warehouse: { code: "WH2" } } } } },
    },
  },
];

export const mockOrders = [
  {
    id: "1",
    orderNumber: "ORD-2026-0001",
    externalId: "#SH-4521",
    channel: "Shopify",
    clientCode: "ACME",
    status: "shipped",
    priority: "standard",
    shipToName: "Jane Cooper",
    shipToCity: "Austin",
    shipToState: "TX",
    totalItems: 3,
    orderDate: new Date("2026-03-10"),
    shipByDate: new Date("2026-03-12"),
  },
  {
    id: "2",
    orderNumber: "ORD-2026-0002",
    externalId: "#AMZ-9982",
    channel: "Amazon",
    clientCode: "ACME",
    status: "picking",
    priority: "expedited",
    shipToName: "Robert Fox",
    shipToCity: "Denver",
    shipToState: "CO",
    totalItems: 1,
    orderDate: new Date("2026-03-15"),
    shipByDate: new Date("2026-03-16"),
  },
  {
    id: "3",
    orderNumber: "ORD-2026-0003",
    externalId: null,
    channel: "Manual",
    clientCode: "GLOBEX",
    status: "awaiting_fulfillment",
    priority: "standard",
    shipToName: "Acme Retail Store #12",
    shipToCity: "Phoenix",
    shipToState: "AZ",
    totalItems: 12,
    orderDate: new Date("2026-03-15"),
    shipByDate: new Date("2026-03-18"),
  },
  {
    id: "4",
    orderNumber: "ORD-2026-0004",
    externalId: "#SH-4530",
    channel: "Shopify",
    clientCode: "STARK",
    status: "awaiting_fulfillment",
    priority: "rush",
    shipToName: "Emily Wilson",
    shipToCity: "Seattle",
    shipToState: "WA",
    totalItems: 2,
    orderDate: new Date("2026-03-16"),
    shipByDate: new Date("2026-03-16"),
  },
  {
    id: "5",
    orderNumber: "ORD-2026-0005",
    externalId: "#WM-1122",
    channel: "Walmart",
    clientCode: "ACME",
    status: "pending",
    priority: "standard",
    shipToName: "Michael Brown",
    shipToCity: "Portland",
    shipToState: "OR",
    totalItems: 5,
    orderDate: new Date("2026-03-16"),
    shipByDate: new Date("2026-03-19"),
  },
  {
    id: "6",
    orderNumber: "ORD-2026-0006",
    externalId: null,
    channel: "API",
    clientCode: "INITECH",
    status: "packed",
    priority: "standard",
    shipToName: "Warehouse Direct LLC",
    shipToCity: "Dallas",
    shipToState: "TX",
    totalItems: 8,
    orderDate: new Date("2026-03-16"),
    shipByDate: new Date("2026-03-18"),
  },
];

export const mockTransactions = [
  {
    id: "1",
    type: "receive",
    product: { sku: "WIDGET-001" },
    fromBin: null,
    toBin: { barcode: "WH1-A-01-01-01-01" },
    quantity: 150,
    lotNumber: null,
    referenceType: "shipment",
    performedAt: new Date("2026-03-10"),
  },
  {
    id: "2",
    type: "receive",
    product: { sku: "GADGET-001" },
    fromBin: null,
    toBin: { barcode: "WH1-A-01-01-01-03" },
    quantity: 75,
    lotNumber: "LOT-2026-001",
    referenceType: "shipment",
    performedAt: new Date("2026-03-10"),
  },
  {
    id: "3",
    type: "putaway",
    product: { sku: "BOLT-M8X40" },
    fromBin: { barcode: "WH1-S-01-01-01-01" },
    toBin: { barcode: "WH1-B-02-01-01-05" },
    quantity: 500,
    lotNumber: "LOT-2026-003",
    referenceType: null,
    performedAt: new Date("2026-03-12"),
  },
  {
    id: "4",
    type: "move",
    product: { sku: "WIDGET-001" },
    fromBin: { barcode: "WH1-A-01-01-01-02" },
    toBin: { barcode: "WH1-A-01-01-01-01" },
    quantity: 50,
    lotNumber: null,
    referenceType: null,
    performedAt: new Date("2026-03-14"),
  },
  {
    id: "5",
    type: "adjust",
    product: { sku: "WIDGET-001" },
    fromBin: null,
    toBin: { barcode: "WH1-A-01-01-01-01" },
    quantity: -2,
    lotNumber: null,
    referenceType: "adjustment",
    performedAt: new Date("2026-03-15"),
  },
  {
    id: "6",
    type: "receive",
    product: { sku: "PIPE-SCH40" },
    fromBin: null,
    toBin: { barcode: "WH1-B-02-02-01-01" },
    quantity: 200,
    lotNumber: "LOT-2026-005",
    referenceType: "shipment",
    performedAt: new Date("2026-03-15"),
  },
  {
    id: "7",
    type: "pick",
    product: { sku: "WIDGET-001" },
    fromBin: { barcode: "WH1-A-01-01-01-01" },
    toBin: null,
    quantity: 3,
    lotNumber: null,
    referenceType: "order",
    performedAt: new Date("2026-03-16"),
  },
];

export const mockAdjustments = [
  {
    id: "1",
    adjustmentNumber: "ADJ-2026-0001",
    type: "cycle_count",
    status: "completed",
    lines: [1, 2, 3],
    reason: "Monthly cycle count - Zone A",
    createdBy: "mock-user-1",
    approvedBy: "mock-user-1",
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "2",
    adjustmentNumber: "ADJ-2026-0002",
    type: "adjustment",
    status: "pending_approval",
    lines: [1],
    reason: "Damaged goods write-off",
    createdBy: "mock-user-1",
    approvedBy: null,
    createdAt: new Date("2026-03-14"),
  },
  {
    id: "3",
    adjustmentNumber: "ADJ-2026-0003",
    type: "cycle_count",
    status: "draft",
    lines: [1, 2, 3, 4, 5],
    reason: "Weekly count - Zone B",
    createdBy: "mock-user-1",
    approvedBy: null,
    createdAt: new Date("2026-03-16"),
  },
];

export const mockDiscrepancies = [
  {
    id: "1",
    shipmentNumber: "ASN-2026-0002",
    type: "shortage",
    description: "Missing 5 units of BOLT-M8X40 from pallet 3",
    expectedQty: 100,
    actualQty: 95,
    status: "open",
    createdAt: new Date("2026-03-15"),
  },
  {
    id: "2",
    shipmentNumber: "ASN-2026-0001",
    type: "damage",
    description: "Water damage on 3 units of WIDGET-001",
    expectedQty: null,
    actualQty: null,
    status: "resolved",
    createdAt: new Date("2026-03-10"),
  },
];

export const mockChannels = [
  {
    id: "1",
    name: "Acme Shopify Store",
    type: "shopify",
    isActive: true,
    orderCount: 142,
    lastSync: "2 min ago",
  },
  {
    id: "2",
    name: "Acme Amazon Seller",
    type: "amazon",
    isActive: true,
    orderCount: 89,
    lastSync: "5 min ago",
  },
  {
    id: "3",
    name: "Globex Walmart",
    type: "walmart",
    isActive: true,
    orderCount: 34,
    lastSync: "15 min ago",
  },
  {
    id: "4",
    name: "Manual Orders",
    type: "manual",
    isActive: true,
    orderCount: 23,
    lastSync: null,
  },
  {
    id: "5",
    name: "Initech API",
    type: "api",
    isActive: false,
    orderCount: 0,
    lastSync: null,
  },
];

// Helper to find by ID
export function findClient(id: string) {
  return mockClients.find((c) => c.id === id) ?? null;
}

export function findProduct(id: string) {
  return mockProducts.find((p) => p.id === id) ?? null;
}

export function findShipment(id: string) {
  return mockShipments.find((s) => s.id === id) ?? null;
}
