export const mockClients = [
  {
    id: "1",
    code: "ACME",
    name: "Acme Corporation",
    contactName: "John Smith",
    contactEmail: "john@acme.com",
    contactPhone: "555-0100",
    address: "456 Commerce St",
    city: "Houston",
    state: "TX",
    country: "US",
    zipCode: "77001",
    taxId: "12-3456789",
    notes: null,
    isActive: true,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "2",
    code: "GLOBEX",
    name: "Globex Industries",
    contactName: "Maria Garcia",
    contactEmail: "maria@globex.com",
    contactPhone: "555-0200",
    address: "789 Industrial Blvd",
    city: "Miami",
    state: "FL",
    country: "US",
    zipCode: "33101",
    taxId: "98-7654321",
    notes: "Temperature-sensitive goods",
    isActive: true,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-03-10"),
  },
  {
    id: "3",
    code: "INITECH",
    name: "Initech Logistics",
    contactName: "Bob Porter",
    contactEmail: "bob@initech.com",
    contactPhone: "555-0300",
    address: "321 Supply Chain Dr",
    city: "Dallas",
    state: "TX",
    country: "US",
    zipCode: "75201",
    taxId: null,
    notes: null,
    isActive: true,
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "4",
    code: "WAYNE",
    name: "Wayne Enterprises",
    contactName: "Lucius Fox",
    contactEmail: "lucius@wayne.com",
    contactPhone: "555-0400",
    address: "1 Wayne Tower",
    city: "Chicago",
    state: "IL",
    country: "US",
    zipCode: "60601",
    taxId: null,
    notes: "Account suspended — pending contract renewal",
    isActive: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "5",
    code: "STARK",
    name: "Stark Shipping Co",
    contactName: "Pepper Potts",
    contactEmail: "pepper@stark.com",
    contactPhone: "555-0500",
    address: "10880 Malibu Point",
    city: "Los Angeles",
    state: "CA",
    country: "US",
    zipCode: "90265",
    taxId: "55-1234567",
    notes: null,
    isActive: true,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-15"),
  },
];

export const mockProducts = [
  {
    id: "1",
    sku: "WIDGET-001",
    name: "Standard Widget",
    description: "Standard steel widget, powder-coated",
    clientId: "1",
    baseUom: "EA",
    weight: 0.5,
    weightUnit: "lb",
    hsCode: "7326.90",
    trackLot: false,
    trackSerial: false,
    minStock: 50,
    maxStock: 500,
    isActive: true,
    client: { code: "ACME", name: "Acme Corporation" },
  },
  {
    id: "2",
    sku: "GADGET-001",
    name: "Premium Gadget",
    description: "Electronic gadget with LCD display",
    clientId: "1",
    baseUom: "EA",
    weight: 1.2,
    weightUnit: "lb",
    hsCode: "8543.70",
    trackLot: true,
    trackSerial: false,
    minStock: 25,
    maxStock: 200,
    isActive: true,
    client: { code: "ACME", name: "Acme Corporation" },
  },
  {
    id: "3",
    sku: "PART-A100",
    name: "Component Part A-100",
    description: "Precision machined component",
    clientId: "1",
    baseUom: "EA",
    weight: 0.1,
    weightUnit: "lb",
    hsCode: "8487.90",
    trackLot: false,
    trackSerial: true,
    minStock: 100,
    maxStock: 1000,
    isActive: true,
    client: { code: "ACME", name: "Acme Corporation" },
  },
  {
    id: "4",
    sku: "BOLT-M8X40",
    name: "M8x40 Hex Bolt",
    description: "Grade 8.8 hex bolt, zinc plated",
    clientId: "2",
    baseUom: "EA",
    weight: 0.025,
    weightUnit: "lb",
    hsCode: "7318.15",
    trackLot: true,
    trackSerial: false,
    minStock: 200,
    maxStock: 5000,
    isActive: true,
    client: { code: "GLOBEX", name: "Globex Industries" },
  },
  {
    id: "5",
    sku: "PIPE-SCH40",
    name: 'Schedule 40 Steel Pipe 2"',
    description: "ASTM A53 Grade B, 2 inch, Schedule 40",
    clientId: "2",
    baseUom: "FT",
    weight: 3.65,
    weightUnit: "lb",
    hsCode: "7304.19",
    trackLot: true,
    trackSerial: false,
    minStock: 100,
    maxStock: 1000,
    isActive: true,
    client: { code: "GLOBEX", name: "Globex Industries" },
  },
  {
    id: "6",
    sku: "VALVE-BV2",
    name: '2" Ball Valve',
    description: "Full port brass ball valve, 2 inch",
    clientId: "3",
    baseUom: "EA",
    weight: 2.8,
    weightUnit: "lb",
    hsCode: "8481.80",
    trackLot: false,
    trackSerial: true,
    minStock: 10,
    maxStock: 100,
    isActive: true,
    client: { code: "INITECH", name: "Initech Logistics" },
  },
  {
    id: "7",
    sku: "MOTOR-3HP",
    name: "3HP Electric Motor",
    description: "TEFC 3-phase motor, 1750 RPM",
    clientId: "5",
    baseUom: "EA",
    weight: 45,
    weightUnit: "lb",
    hsCode: "8501.52",
    trackLot: false,
    trackSerial: true,
    minStock: 5,
    maxStock: 20,
    isActive: false,
    client: { code: "STARK", name: "Stark Shipping" },
  },
];

export const mockWarehouses = [
  {
    id: "1",
    code: "WH1",
    name: "Main Warehouse",
    address: "123 Logistics Ave, Houston TX",
    isActive: true,
    zones: [
      {
        id: "z1",
        code: "A",
        name: "Zone A - General Storage",
        type: "storage",
        binCount: 80,
      },
      { id: "z2", code: "B", name: "Zone B - Bulk Storage", type: "storage", binCount: 32 },
      { id: "z3", code: "S", name: "Staging Area", type: "staging", binCount: 16 },
    ],
  },
  {
    id: "2",
    code: "WH2",
    name: "Cold Storage Annex",
    address: "125 Logistics Ave, Houston TX",
    isActive: true,
    zones: [
      { id: "z4", code: "C", name: "Cold Zone", type: "storage", binCount: 48 },
      { id: "z5", code: "D", name: "Dock Area", type: "dock", binCount: 8 },
    ],
  },
];
