export const mockShipments = [
  {
    id: "1",
    shipmentNumber: "ASN-2026-0001",
    status: "completed",
    carrier: "FedEx Freight",
    trackingNumber: "FXF-123456789",
    bolNumber: "BOL-2026-0038",
    poNumber: "PO-ACME-5678",
    expectedDate: "2026-03-10",
    arrivedDate: "2026-03-10",
    completedDate: "2026-03-10",
    notes: null,
    createdAt: "2026-03-08",
    clientId: "1",
    client: { code: "ACME", name: "Acme Corporation" },
    _count: { lines: 3, transactions: 5, discrepancies: 0 },
  },
  {
    id: "2",
    shipmentNumber: "ASN-2026-0002",
    status: "receiving",
    carrier: "XPO Logistics",
    trackingNumber: "XPO-789456123",
    bolNumber: "BOL-2026-0042",
    poNumber: "PO-GLX-1234",
    expectedDate: "2026-03-15",
    arrivedDate: "2026-03-15",
    completedDate: null,
    notes: "Fragile items — handle with care. Dock door 3.",
    createdAt: "2026-03-12",
    clientId: "2",
    client: { code: "GLOBEX", name: "Globex Industries" },
    _count: { lines: 5, transactions: 2, discrepancies: 1 },
  },
  {
    id: "3",
    shipmentNumber: "ASN-2026-0003",
    status: "arrived",
    carrier: "SAIA",
    trackingNumber: "SAIA-456789012",
    bolNumber: "BOL-2026-0045",
    poNumber: null,
    expectedDate: "2026-03-16",
    arrivedDate: "2026-03-16",
    completedDate: null,
    notes: null,
    createdAt: "2026-03-13",
    clientId: "3",
    client: { code: "INITECH", name: "Initech Logistics" },
    _count: { lines: 2, transactions: 0, discrepancies: 0 },
  },
  {
    id: "4",
    shipmentNumber: "ASN-2026-0004",
    status: "expected",
    carrier: "Old Dominion",
    trackingNumber: null,
    bolNumber: null,
    poNumber: "PO-STK-9012",
    expectedDate: "2026-03-18",
    arrivedDate: null,
    completedDate: null,
    notes: "24 pallets, requires forklift",
    createdAt: "2026-03-14",
    clientId: "5",
    client: { code: "STARK", name: "Stark Shipping Co" },
    _count: { lines: 4, transactions: 0, discrepancies: 0 },
  },
  {
    id: "5",
    shipmentNumber: "ASN-2026-0005",
    status: "draft",
    carrier: null,
    trackingNumber: null,
    bolNumber: null,
    poNumber: null,
    expectedDate: null,
    arrivedDate: null,
    completedDate: null,
    notes: null,
    createdAt: "2026-03-16",
    clientId: "1",
    client: { code: "ACME", name: "Acme Corporation" },
    _count: { lines: 0, transactions: 0, discrepancies: 0 },
  },
];

export const mockInventory = [
  {
    id: "1",
    onHand: 150,
    allocated: 20,
    available: 130,
    lotNumber: null,
    serialNumber: null,
    uom: "EA",
    product: { sku: "WIDGET-001", name: "Standard Widget", client: { code: "ACME" } },
    bin: {
      barcode: "WH1-A-01-01-01-01",
      shelf: { rack: { aisle: { zone: { code: "A", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "2",
    onHand: 75,
    allocated: 0,
    available: 75,
    lotNumber: "LOT-2026-001",
    serialNumber: null,
    uom: "EA",
    product: { sku: "GADGET-001", name: "Premium Gadget", client: { code: "ACME" } },
    bin: {
      barcode: "WH1-A-01-01-01-03",
      shelf: { rack: { aisle: { zone: { code: "A", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "3",
    onHand: 500,
    allocated: 100,
    available: 400,
    lotNumber: "LOT-2026-003",
    serialNumber: null,
    uom: "EA",
    product: { sku: "BOLT-M8X40", name: "M8x40 Hex Bolt", client: { code: "GLOBEX" } },
    bin: {
      barcode: "WH1-B-02-01-01-05",
      shelf: { rack: { aisle: { zone: { code: "B", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "4",
    onHand: 30,
    allocated: 5,
    available: 25,
    lotNumber: null,
    serialNumber: "SN-00234",
    uom: "EA",
    product: { sku: "VALVE-BV2", name: '2" Ball Valve', client: { code: "INITECH" } },
    bin: {
      barcode: "WH1-A-01-02-01-02",
      shelf: { rack: { aisle: { zone: { code: "A", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "5",
    onHand: 200,
    allocated: 0,
    available: 200,
    lotNumber: "LOT-2026-005",
    serialNumber: null,
    uom: "FT",
    product: {
      sku: "PIPE-SCH40",
      name: 'Schedule 40 Steel Pipe 2"',
      client: { code: "GLOBEX" },
    },
    bin: {
      barcode: "WH1-B-02-02-01-01",
      shelf: { rack: { aisle: { zone: { code: "B", warehouse: { code: "WH1" } } } } },
    },
  },
  {
    id: "6",
    onHand: 0,
    allocated: 0,
    available: 0,
    lotNumber: null,
    serialNumber: null,
    uom: "EA",
    product: { sku: "MOTOR-3HP", name: "3HP Electric Motor", client: { code: "STARK" } },
    bin: {
      barcode: "WH2-C-01-01-01-01",
      shelf: { rack: { aisle: { zone: { code: "C", warehouse: { code: "WH2" } } } } },
    },
  },
];

export const mockOrders = [
  {
    id: "1",
    orderNumber: "ORD-2026-0001",
    externalId: "#SH-4521",
    channel: "Shopify",
    clientCode: "ACME",
    status: "shipped",
    priority: "standard",
    shipToName: "Jane Cooper",
    shipToCity: "Austin",
    shipToState: "TX",
    totalItems: 3,
    orderDate: new Date("2026-03-10"),
    shipByDate: new Date("2026-03-12"),
  },
  {
    id: "2",
    orderNumber: "ORD-2026-0002",
    externalId: "#AMZ-9982",
    channel: "Amazon",
    clientCode: "ACME",
    status: "picking",
    priority: "expedited",
    shipToName: "Robert Fox",
    shipToCity: "Denver",
    shipToState: "CO",
    totalItems: 1,
    orderDate: new Date("2026-03-15"),
    shipByDate: new Date("2026-03-16"),
  },
  {
    id: "3",
    orderNumber: "ORD-2026-0003",
    externalId: null,
    channel: "Manual",
    clientCode: "GLOBEX",
    status: "awaiting_fulfillment",
    priority: "standard",
    shipToName: "Acme Retail Store #12",
    shipToCity: "Phoenix",
    shipToState: "AZ",
    totalItems: 12,
    orderDate: new Date("2026-03-15"),
    shipByDate: new Date("2026-03-18"),
  },
  {
    id: "4",
    orderNumber: "ORD-2026-0004",
    externalId: "#SH-4530",
    channel: "Shopify",
    clientCode: "STARK",
    status: "awaiting_fulfillment",
    priority: "rush",
    shipToName: "Emily Wilson",
    shipToCity: "Seattle",
    shipToState: "WA",
    totalItems: 2,
    orderDate: new Date("2026-03-16"),
    shipByDate: new Date("2026-03-16"),
  },
  {
    id: "5",
    orderNumber: "ORD-2026-0005",
    externalId: "#WM-1122",
    channel: "Walmart",
    clientCode: "ACME",
    status: "pending",
    priority: "standard",
    shipToName: "Michael Brown",
    shipToCity: "Portland",
    shipToState: "OR",
    totalItems: 5,
    orderDate: new Date("2026-03-16"),
    shipByDate: new Date("2026-03-19"),
  },
  {
    id: "6",
    orderNumber: "ORD-2026-0006",
    externalId: null,
    channel: "API",
    clientCode: "INITECH",
    status: "packed",
    priority: "standard",
    shipToName: "Warehouse Direct LLC",
    shipToCity: "Dallas",
    shipToState: "TX",
    totalItems: 8,
    orderDate: new Date("2026-03-16"),
    shipByDate: new Date("2026-03-18"),
  },
];

export const mockTransactions = [
  {
    id: "1",
    type: "receive",
    product: { sku: "WIDGET-001" },
    fromBin: null,
    toBin: { barcode: "WH1-A-01-01-01-01" },
    quantity: 150,
    lotNumber: null,
    referenceType: "shipment",
    performedAt: new Date("2026-03-10"),
  },
  {
    id: "2",
    type: "receive",
    product: { sku: "GADGET-001" },
    fromBin: null,
    toBin: { barcode: "WH1-A-01-01-01-03" },
    quantity: 75,
    lotNumber: "LOT-2026-001",
    referenceType: "shipment",
    performedAt: new Date("2026-03-10"),
  },
  {
    id: "3",
    type: "putaway",
    product: { sku: "BOLT-M8X40" },
    fromBin: { barcode: "WH1-S-01-01-01-01" },
    toBin: { barcode: "WH1-B-02-01-01-05" },
    quantity: 500,
    lotNumber: "LOT-2026-003",
    referenceType: null,
    performedAt: new Date("2026-03-12"),
  },
  {
    id: "4",
    type: "move",
    product: { sku: "WIDGET-001" },
    fromBin: { barcode: "WH1-A-01-01-01-02" },
    toBin: { barcode: "WH1-A-01-01-01-01" },
    quantity: 50,
    lotNumber: null,
    referenceType: null,
    performedAt: new Date("2026-03-14"),
  },
  {
    id: "5",
    type: "adjust",
    product: { sku: "WIDGET-001" },
    fromBin: null,
    toBin: { barcode: "WH1-A-01-01-01-01" },
    quantity: -2,
    lotNumber: null,
    referenceType: "adjustment",
    performedAt: new Date("2026-03-15"),
  },
  {
    id: "6",
    type: "receive",
    product: { sku: "PIPE-SCH40" },
    fromBin: null,
    toBin: { barcode: "WH1-B-02-02-01-01" },
    quantity: 200,
    lotNumber: "LOT-2026-005",
    referenceType: "shipment",
    performedAt: new Date("2026-03-15"),
  },
  {
    id: "7",
    type: "pick",
    product: { sku: "WIDGET-001" },
    fromBin: { barcode: "WH1-A-01-01-01-01" },
    toBin: null,
    quantity: 3,
    lotNumber: null,
    referenceType: "order",
    performedAt: new Date("2026-03-16"),
  },
];
