export const mockAdjustments = [
  {
    id: "1",
    adjustmentNumber: "ADJ-2026-0001",
    type: "cycle_count",
    status: "completed",
    lines: [1, 2, 3],
    reason: "Monthly cycle count - Zone A",
    createdBy: "mock-user-1",
    approvedBy: "mock-user-1",
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "2",
    adjustmentNumber: "ADJ-2026-0002",
    type: "adjustment",
    status: "pending_approval",
    lines: [1],
    reason: "Damaged goods write-off",
    createdBy: "mock-user-1",
    approvedBy: null,
    createdAt: new Date("2026-03-14"),
  },
  {
    id: "3",
    adjustmentNumber: "ADJ-2026-0003",
    type: "cycle_count",
    status: "draft",
    lines: [1, 2, 3, 4, 5],
    reason: "Weekly count - Zone B",
    createdBy: "mock-user-1",
    approvedBy: null,
    createdAt: new Date("2026-03-16"),
  },
];

export const mockDiscrepancies = [
  {
    id: "1",
    shipmentNumber: "ASN-2026-0002",
    type: "shortage",
    description: "Missing 5 units of BOLT-M8X40 from pallet 3",
    expectedQty: 100,
    actualQty: 95,
    status: "open",
    createdAt: new Date("2026-03-15"),
  },
  {
    id: "2",
    shipmentNumber: "ASN-2026-0001",
    type: "damage",
    description: "Water damage on 3 units of WIDGET-001",
    expectedQty: null,
    actualQty: null,
    status: "resolved",
    createdAt: new Date("2026-03-10"),
  },
];

export const mockChannels = [
  {
    id: "1",
    name: "Acme Shopify Store",
    type: "shopify",
    isActive: true,
    orderCount: 142,
    lastSync: "2 min ago",
  },
  {
    id: "2",
    name: "Acme Amazon Seller",
    type: "amazon",
    isActive: true,
    orderCount: 89,
    lastSync: "5 min ago",
  },
  {
    id: "3",
    name: "Globex Walmart",
    type: "walmart",
    isActive: true,
    orderCount: 34,
    lastSync: "15 min ago",
  },
  {
    id: "4",
    name: "Manual Orders",
    type: "manual",
    isActive: true,
    orderCount: 23,
    lastSync: null,
  },
  {
    id: "5",
    name: "Initech API",
    type: "api",
    isActive: false,
    orderCount: 0,
    lastSync: null,
  },
];
